#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# TOKYO NIGHT
bspc config border_width         1
bspc config window_gap           9
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color "#44475a"
bspc config focused_border_color "#2ac3de"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# WALLPAPER
${HOME}/.fehbg

# EXTRAS
/usr/bin/numlockx on
xsetroot -cursor_name left_ptr

# RUN POLYBAR
${HOME}/.config/polybar/launch.sh &

# TRANSPARENCY
picom &
